/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_foxteam_noisyfox_FoxGaming_Core_FGNativeHelper */

#ifndef _Included_org_foxteam_noisyfox_FoxGaming_Core_FGNativeHelper
#define _Included_org_foxteam_noisyfox_FoxGaming_Core_FGNativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_foxteam_noisyfox_FoxGaming_Core_FGNativeHelper
 * Method:    initalizeJNINative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_foxteam_noisyfox_FoxGaming_Core_FGNativeHelper_initalizeJNINative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
