/*
 * MethodDefinations.h
 *
 *  Created on: 2013-1-18
 *      Author: Noisyfox
 */

#include <ParticleSystem.h>

#ifndef METHODDEFINATIONS_H_
#define METHODDEFINATIONS_H_
#ifdef __cplusplus
extern "C" {
#endif

#define JNIREG_CLASS_ParticleSystem "org/foxteam/noisyfox/FoxGaming/G2D/Particle/FGParticleNative"//指定要注册的类
JNINativeMethod gMethods_ParticleSystem[] =
		{
				{ "PScreateParticleSystemNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PScreateParticleSystemNative },
				{ "PSupdateNative", "(J)Ljava/nio/ByteBuffer;",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSupdateNative },
				{ "PSgetParticlesNative", "(J)Ljava/nio/ByteBuffer;",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSgetParticlesNative },
				{ "PScreateParticleNative", "(JJIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PScreateParticleNative__JJIII },
				{ "PScreateParticleNative", "(JJIIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PScreateParticleNative__JJIIII },
				{ "PSclearNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSclearNative },
				{ "PScountNative", "(J)I",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PScountNative },
				{ "PSsetMaxParticleNumberNative", "(JI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSsetMaxParticleNumberNative },
				{ "PSbindParticleEmitterNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSbindParticleEmitterNative },
				{ "PSbindParticleAttractorNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSbindParticleAttractorNative },
				{ "PSbindPraticleDestroyerNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSbindPraticleDestroyerNative },
				{ "PSbindPraticleDeflectorNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSbindPraticleDeflectorNative },
				{ "PSbindParticleChangerNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSbindParticleChangerNative },
				{ "PSunbindParticleEmitterNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSunbindParticleEmitterNative },
				{ "PSunbindParticleAttractorNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSunbindParticleAttractorNative },
				{ "PSunbindPraticleDestroyerNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSunbindPraticleDestroyerNative },
				{ "PSunbindPraticleDeflectorNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSunbindPraticleDeflectorNative },
				{ "PSunbindParticleChangerNative", "(JJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSunbindParticleChangerNative },
				{ "PSremoveParticleSystemNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSremoveParticleSystemNative },
				{ "PSfinalizeParticleSystemNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PSfinalizeParticleSystemNative },
				{ "PTcreateParticleTypeNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTcreateParticleTypeNative },
				{ "PTsetSpriteParameterNative", "(JI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetSpriteParameterNative },
				{ "PTsetSpriteFrameAnimationNative", "(JZDZ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetSpriteFrameAnimationNative },
				{ "PTsetSizeNative", "(JDDDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetSizeNative },
				{ "PTsetScaleNative", "(JFF)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetScaleNative },
				{ "PTsetOrientationNative", "(JFFDDZ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetOrientationNative },
				{ "PTsetColorNative", "(JI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetColorNative__JI },
				{ "PTsetColorNative", "(JII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetColorNative__JII },
				{ "PTsetColorNative", "(JIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetColorNative__JIII },
				{ "PTsetColorRGBNative", "(JIIIIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetColorRGBNative },
				{ "PTsetColorHSVNative", "(JIDDIDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetColorHSVNative },
				{ "PTsetAlphaNative", "(JD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetAlphaNative__JD },
				{ "PTsetAlphaNative", "(JDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetAlphaNative__JDD },
				{ "PTsetAlphaNative", "(JDDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetAlphaNative__JDDD },
				{ "PTsetLifeTimeNative", "(JII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetLifeTimeNative },
				{ "PTcreateNewParticleOnStepNative", "(JZJI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTcreateNewParticleOnStepNative },
				{ "PTcreateNewParticleOnDeathNative", "(JZJI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTcreateNewParticleOnDeathNative },
				{ "PTsetSpeedNative", "(JDDDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetSpeedNative },
				{ "PTsetDirectionNative", "(JDDDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetDirectionNative },
				{ "PTsetGravityNative", "(JDD)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTsetGravityNative },
				{ "PTremoveParticleTypeNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTremoveParticleTypeNative },
				{ "PTfinalizeParticleTypeNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PTfinalizeParticleTypeNative },
				{ "PAcreateParticleAttractorNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAcreateParticleAttractorNative },
				{ "PAsetPositionNative", "(JII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAsetPositionNative },
				{ "PAsetForceNative", "(JIFFZ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAsetForceNative },
				{ "PAremoveParticleAttractorNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAremoveParticleAttractorNative },
				{ "PAfinalizeParticleAttractorNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAfinalizeParticleAttractorNative },
				{ "PCcreateParticleChangerNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCcreateParticleChangerNative },
				{ "PCsetRegionNative", "(JIIIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCsetRegionNative },
				{ "PCsetParticleTypesNative", "(JJJ)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCsetParticleTypesNative },
				{ "PCsetChangerKindNative", "(JI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCsetChangerKindNative },
				{ "PCremoveParticleChangerNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCremoveParticleChangerNative },
				{ "PCfinalizeParticleChangerNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PCfinalizeParticleChangerNative },
				{ "PDcreateParticleDestroyerNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PDcreateParticleDestroyerNative },
				{ "PDsetRegionNative", "(JIIIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PDsetRegionNative },
				{ "PDremoveParticleDestroyerNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PDremoveParticleDestroyerNative },
				{ "PDfinalizeParticleDestroyerNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PDfinalizeParticleDestroyerNative },
				{ "PEcreateParticleEmitterNative", "()J",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEcreateParticleEmitterNative },
				{ "PEsetRegionNative", "(JIIIIII)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEsetRegionNative },
				{ "PEburstNative", "(JJI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEburstNative },
				{ "PEstreamNative", "(JJI)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEstreamNative },
				{ "PEremoveParticleEmitterNative", "(J)Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEremoveParticleEmitterNative },
				{ "PEfinalizeParticleEmitterNative", "()Z",
						(void*) Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PEfinalizeParticleEmitterNative }, };
#ifdef __cplusplus
}
#endif
#endif /* METHODDEFINATIONS_H_ */
