/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative */

#ifndef _Included_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
#define _Included_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
#ifdef __cplusplus
extern "C" {
#endif
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_LINEAR
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_LINEAR 1L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_GAUSSIAN
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_GAUSSIAN 2L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_INVGAUSSIAN
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_DISTRIBUTION_INVGAUSSIAN 3L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_RECTANGLE
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_RECTANGLE 4L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_ELLIPSE
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_ELLIPSE 5L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_DIAMOND
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_REGION_SHAPE_DIAMOND 6L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_CONSTANT
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_CONSTANT 7L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_LINEAR
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_LINEAR 8L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_QUADRATIC
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_FORCE_QUADRATIC 9L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_MOTION
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_MOTION 10L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_SHAPE
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_SHAPE 11L
#undef org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_ALL
#define org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_PAR_CHANGE_ALL 12L
/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    createParticleSystemNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_createParticleSystemNative
  (JNIEnv *, jclass);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    removeParticleNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_removeParticleNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    obtainParticleNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_obtainParticleNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    updateNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_updateNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    createParticleNative
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_createParticleNative
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    clearNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_clearNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    countNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_countNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    setMaxParticleNumberNative
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_setMaxParticleNumberNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_foxteam_noisyfox_FoxGaming_G2D_Particle_FGParticleNative_finalizeNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
